### ISSUE TITLE
Section 2.5.3 code cleanup opportunity

### ISSUE THREAD

**Issue by alecglen** [bcongelio/nfl-analytics-with-r-book#10]
From an nflverse Discord comment:

hey @bcongelio looking at this section in the book (2.5.3) - is the additional filter to exclude NAs on the down necessary since you're already asking for a specific down?

<img width="756" alt="image" src="https://github.com/bcongelio/nfl-analytics-with-r-book/assets/28493454/b4424055-6cbe-4b8f-a771-4501b840b0a1">

**Comment by bcongelio** [comment]
Good find. The `is.na(down)` is not needed since `down == 3` is present. Adding the 'editorial changes' label and will complete this during the page proof process.

**Comment by bcongelio** [comment]
Completed in page proofs.
