### ISSUE TITLE
Chapter 4.6

### ISSUE THREAD

**Issue by Timboslice003** [bcongelio/nfl-analytics-with-r-book#16]
"When charting passing attempts in football, a player’s individual passing yards are aggregated under gross yards with all lost yardage resulting from a sack being included. On the other hand, team passing yards are always presented in net yards and any lost yardage from sacks are not included. "

Shouldn't this be the other way around. Doesn't net yards include sacks and gross yards excludes sacks?

**Comment by bcongelio** [comment]
The definitions as presented in the book came from Pro Football Reference, as I had to verify that difference myself:

> Confusingly, sack yards do not count against the "passing yards" you see listed next to individual players, but they do count against "passing yards" at the team level. To put it another way, individual passing yards are always presented as GROSS yards (with sack yards not subtracted out), while team passing yards are always presented as NET yards (meaning sack yards are subtracted out).
